import os
import logging
from datetime import datetime
from typing import Dict, Any, Optional, List
from sqlalchemy import create_engine, Column, String, DateTime, Float, Text, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

Base = declarative_base()

class DecisionLog(Base):
    """
    SQLAlchemy model for storing agent decisions and confidence scores.
    """
    __tablename__ = "decision_logs"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    agent_name = Column(String(100), nullable=False)
    input_data = Column(Text, nullable=False)
    agent_output = Column(Text, nullable=False)
    confidence_score = Column(Float, nullable=False)
    model_used = Column(String(50), nullable=True)
    fallback_triggered = Column(String(10), nullable=False, default="false")
    processing_time = Column(Float, nullable=True)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert DecisionLog to dictionary."""
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "agent_name": self.agent_name,
            "input_data": self.input_data,
            "agent_output": self.agent_output,
            "confidence_score": self.confidence_score,
            "model_used": self.model_used,
            "fallback_triggered": self.fallback_triggered,
            "processing_time": self.processing_time
        }

class DatabaseManager:
    """
    Database manager for handling SQLAlchemy operations.
    """
    
    def __init__(self):
        self.database_url = os.getenv("DATABASE_URL", "sqlite:///data/decision_logs.db")
        self.engine = create_engine(self.database_url)
        self.SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=self.engine)
        self.create_tables()
    
    def create_tables(self):
        """Create all database tables."""
        try:
            Base.metadata.create_all(bind=self.engine)
            logger.info("Database tables created successfully")
        except Exception as e:
            logger.error(f"Failed to create database tables: {e}")
    
    def get_session(self) -> Session:
        """Get a database session."""
        return self.SessionLocal()
    
    def log_decision(self, 
                    agent_name: str,
                    input_data: str,
                    agent_output: str,
                    confidence_score: float,
                    model_used: Optional[str] = None,
                    fallback_triggered: bool = False,
                    processing_time: Optional[float] = None) -> DecisionLog:
        """
        Log a decision to the database.
        
        Args:
            agent_name: Name of the agent that made the decision
            input_data: Input data provided to the agent
            agent_output: Output generated by the agent
            confidence_score: Confidence score (0-100)
            model_used: Which model was used (ollama/openai)
            fallback_triggered: Whether fallback was triggered
            processing_time: Time taken for processing in seconds
            
        Returns:
            DecisionLog object
        """
        session = self.get_session()
        try:
            decision_log = DecisionLog(
                agent_name=agent_name,
                input_data=input_data,
                agent_output=agent_output,
                confidence_score=confidence_score,
                model_used=model_used,
                fallback_triggered="true" if fallback_triggered else "false",
                processing_time=processing_time
            )
            
            session.add(decision_log)
            session.commit()
            session.refresh(decision_log)
            
            logger.info(f"Decision logged for agent {agent_name} with confidence {confidence_score}%")
            return decision_log
            
        except Exception as e:
            session.rollback()
            logger.error(f"Failed to log decision: {e}")
            raise
        finally:
            session.close()
    
    def get_recent_decisions(self, limit: int = 100, agent_name: Optional[str] = None) -> List[DecisionLog]:
        """
        Get recent decisions from the database.
        
        Args:
            limit: Maximum number of decisions to retrieve
            agent_name: Optional filter for specific agent
            
        Returns:
            List of DecisionLog objects
        """
        session = self.get_session()
        try:
            query = session.query(DecisionLog).order_by(DecisionLog.timestamp.desc())
            
            if agent_name:
                query = query.filter(DecisionLog.agent_name == agent_name)
            
            decisions = query.limit(limit).all()
            return decisions
            
        except Exception as e:
            logger.error(f"Failed to retrieve decisions: {e}")
            return []
        finally:
            session.close()
    
    def get_decision_stats(self, agent_name: Optional[str] = None) -> Dict[str, Any]:
        """
        Get statistics about decisions.
        
        Args:
            agent_name: Optional filter for specific agent
            
        Returns:
            Dictionary with decision statistics
        """
        session = self.get_session()
        try:
            query = session.query(DecisionLog)
            
            if agent_name:
                query = query.filter(DecisionLog.agent_name == agent_name)
            
            total_decisions = query.count()
            avg_confidence = session.query(DecisionLog.confidence_score).filter(
                DecisionLog.agent_name == agent_name if agent_name else True
            ).all()
            
            if avg_confidence:
                avg_confidence_value = sum(score[0] for score in avg_confidence) / len(avg_confidence)
            else:
                avg_confidence_value = 0
            
            fallback_count = query.filter(DecisionLog.fallback_triggered == "true").count()
            fallback_rate = (fallback_count / total_decisions * 100) if total_decisions > 0 else 0
            
            return {
                "total_decisions": total_decisions,
                "average_confidence": round(avg_confidence_value, 2),
                "fallback_count": fallback_count,
                "fallback_rate": round(fallback_rate, 2),
                "agent_filter": agent_name
            }
            
        except Exception as e:
            logger.error(f"Failed to get decision stats: {e}")
            return {}
        finally:
            session.close()

# Singleton instance
db_manager = DatabaseManager()

def get_db_manager() -> DatabaseManager:
    """Get the singleton DatabaseManager instance."""
    return db_manager

def log_decision(agent_name: str, input_data: str, agent_output: str, confidence_score: float, **kwargs) -> DecisionLog:
    """Convenience function to log a decision."""
    return db_manager.log_decision(agent_name, input_data, agent_output, confidence_score, **kwargs)