import os
from fpdf import FPDF
from datetime import datetime

class ACRISReport(FPDF):
    def header(self):
        # Logo placeholder or branding
        self.set_fill_color(30, 41, 59) # Slate 800
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, "ACRIS", ln=True, align="L")
        
        self.set_font("Helvetica", "I", 10)
        self.cell(0, 5, "Autonomous Compliance & Regulatory Intelligence System", ln=True, align="L")
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by ACRIS AI Engine | {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

def generate_pdf():
    pdf = ACRISReport()
    pdf.add_page()
    
    # Title Section
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, "Internal Policy Alignment & Gap Analysis", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 10, "Target Document: Indian_Bank_KYC_Policy_v4.2.pdf", ln=True)
    pdf.ln(5)
    
    # Executive Summary Box
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(10, pdf.get_y(), 190, 40, 'FD')
    
    pdf.set_y(pdf.get_y() + 5)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(0, 8, "EXECUTIVE SUMMARY", ln=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(15)
    pdf.cell(0, 6, "- Semantic Accuracy Score: 92%", ln=True)
    pdf.set_x(15)
    pdf.cell(0, 6, "- Clauses Mapped: 42 across 24 Regulation Vectors", ln=True)
    pdf.set_x(15)
    pdf.set_text_color(225, 29, 72) # Red 600
    pdf.cell(0, 6, "- CRITICAL GAP: 1 Contradiction identified in Onboarding Directive.", ln=True)
    pdf.ln(10)

    # Detailed Findings
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, "1. Mapping Detail: KYC & Onboarding", ln=True)
    
    # Table Header
    pdf.set_fill_color(79, 70, 229) # Indigo 600
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    
    col_width = 190 / 3
    pdf.cell(30, 10, "Clause ID", 1, 0, 'C', True)
    pdf.cell(80, 10, "Internal Mandate", 1, 0, 'C', True)
    pdf.cell(80, 10, "Regulatory Status", 1, 1, 'C', True)
    
    # Table Content
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Helvetica", "", 9)
    
    data = [
        ("14.2", "Physical signature mandatory on all 'High Risk' account forms.", "CONTRADICTED: RBI/2024/73 allows fully automated Video-KYC (V-CIP) for all risk categories."),
        ("15.1", "Aadhaar masking required for storage.", "COMPLIANT: Verified against UIDAI 2023 Circular."),
        ("18.4", "Quarterly audit of third-party agents.", "IMPROVED: RBI recommends real-time API monitoring instead of bulk quarterly audits.")
    ]
    
    for row in data:
        # Calculate heights for wrap
        pdf.cell(30, 10, row[0], 1)
        pdf.cell(80, 10, row[1][:45] + "...", 1)
        pdf.cell(80, 10, row[2][:45] + "...", 1)
        pdf.ln()

    pdf.ln(10)
    
    # Recommendation Section
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, "AI-Generated Recommendations", ln=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    recommendation_text = (
        "Based on the identified KYC contradiction, the 'Drafting Agent' suggests the following amendment: \n\n"
        "REPLACE Clause 14.2 WITH: 'Customer onboarding may be conducted via Video-based Customer Identification Process (V-CIP) "
        "as per RBI Master Direction (Updated 2024). Human manual intervention is only required if the AI Match score is <85%.'"
    )
    pdf.multi_cell(0, 6, recommendation_text, border=1)
    
    # Audit Trail
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 8, "TECHNICAL AUDIT TRAIL", ln=True)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, "Engine: ACRIS Semantic Layer v2.1", ln=True)
    pdf.cell(0, 5, "Model: Gemini 3.1 Pro (via ModelRouter)", ln=True)
    pdf.cell(0, 5, f"Analysis Hash: {datetime.now().strftime('%H%M%S%f')}", ln=True)

    # Save
    os.makedirs("reports", exist_ok=True)
    report_path = os.path.join("reports", "ACRIS_Compliance_Report_April2026.pdf")
    pdf.output(report_path)
    print(f"Report generated successfully at: {report_path}")

if __name__ == "__main__":
    generate_pdf()
